services:
  - type: web
    name: mail-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: REDIRECT_URI
        value: https://mail-ai-9ojz.onrender.com/oauth2callback
